services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./app/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/docker   
    depends_on:
      - mongodb

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5050

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
