apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5050           # Service port
      targetPort: 5050     # Container port
      nodePort: 30001      # External port (customizable)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:local
          ports:
            - containerPort: 5050
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/docker
