apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:local
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/docker

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5050
      targetPort: 5050
  type: ClusterIP
