version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5050:5050"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dockers
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
